#!/usr/bin/env python3
"""Generates Soundflow/UI/Theme/LucideGlyphs.swift from lucide-static SVGs.

Every icon in Assets.xcassets/Icons is converted into a list of SVG path strings, one per
element, so the app can animate the parts of an icon independently.

Usage: scripts/gen_lucide_glyphs.py <path-to-lucide-static/icons>
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "Soundflow/Resources/Assets.xcassets/Icons")
OUTPUT = os.path.join(ROOT, "Soundflow/UI/Theme/LucideGlyphs.swift")


def num(value):
    return float(value or 0)


def fmt(value):
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return text if text not in ("-0", "") else "0"


def element_to_path(el):
    tag = el.tag.split("}")[-1]
    a = el.attrib
    if tag == "path":
        return a["d"]
    if tag == "circle":
        cx, cy, r = num(a.get("cx")), num(a.get("cy")), num(a.get("r"))
        return (f"M{fmt(cx - r)} {fmt(cy)}a{fmt(r)} {fmt(r)} 0 1 0 {fmt(2 * r)} 0"
                f"a{fmt(r)} {fmt(r)} 0 1 0 {fmt(-2 * r)} 0z")
    if tag == "ellipse":
        cx, cy, rx, ry = num(a.get("cx")), num(a.get("cy")), num(a.get("rx")), num(a.get("ry"))
        return (f"M{fmt(cx - rx)} {fmt(cy)}a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(2 * rx)} 0"
                f"a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(-2 * rx)} 0z")
    if tag == "rect":
        x, y, w, h = num(a.get("x")), num(a.get("y")), num(a.get("width")), num(a.get("height"))
        rx = num(a.get("rx", a.get("ry", 0)))
        ry = num(a.get("ry", a.get("rx", 0)))
        if rx == 0:
            return f"M{fmt(x)} {fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}z"
        return (f"M{fmt(x + rx)} {fmt(y)}h{fmt(w - 2 * rx)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(ry)}"
                f"v{fmt(h - 2 * ry)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(ry)}h{fmt(-(w - 2 * rx))}"
                f"a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(-ry)}v{fmt(-(h - 2 * ry))}"
                f"a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(-ry)}z")
    if tag == "line":
        return f"M{a['x1']} {a['y1']}L{a['x2']} {a['y2']}"
    if tag in ("polyline", "polygon"):
        points = re.findall(r"-?[\d.]+", a["points"])
        pairs = [f"{points[i]} {points[i + 1]}" for i in range(0, len(points), 2)]
        return "M" + "L".join(pairs) + ("z" if tag == "polygon" else "")
    raise ValueError(f"unsupported element {tag}")


def main():
    source = sys.argv[1]
    names = sorted(d[len("lucide."):-len(".imageset")] for d in os.listdir(ASSETS) if d.endswith(".imageset"))
    lines = [
        "// Generated by scripts/gen_lucide_glyphs.py from lucide-static (ISC License). Do not edit.",
        "",
        "enum LucideGlyphs {",
        "    /// SVG path data per icon, one entry per drawn element, in a 24×24 coordinate space.",
        "    static let paths: [String: [String]] = [",
    ]
    for name in names:
        tree = ET.parse(os.path.join(source, f"{name}.svg"))
        parts = [element_to_path(el) for el in tree.getroot()]
        joined = ", ".join('"' + p.replace('"', '\\"') + '"' for p in parts)
        lines.append(f'        "{name}": [{joined}],')
    lines += ["    ]", "}", ""]
    with open(OUTPUT, "w") as out:
        out.write("\n".join(lines))
    print(f"{len(names)} icons → {os.path.relpath(OUTPUT, ROOT)}")


if __name__ == "__main__":
    main()
